platform :ios, '9.0'
use_frameworks!

target 'ResponderMessenger_Example' do
  pod 'ResponderMessenger', :path => '../'

  target 'ResponderMessenger_Tests' do
    inherit! :search_paths

    pod 'ResponderMessenger', :path => '../'
  end
end
